GET https://localhost:4000/protected-resource

Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlJJNkp3OWs3WUR0cUs0ZldOQk1ZbUEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1ODIzMzk3NjEsImV4cCI6MTU4MjM0MzM2MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6IkNsaWVudENyZWRlbnRpYWxBcHAiLCJjbGllbnRfaWQiOiJjbGllbnRfaWQiLCJzY29wZSI6WyJDbGllbnRDcmVkZW50aWFsQXBwIl19.T8mVQDECVOaGiBQ_nBk7uCfFlgBfmhVAAnMP56scnjaX0e9bi8QMA99PUisKrqfQQ1d9R6d0t-DM2ygTOjdkDnbPNWjDxHcGDNL7RGC5jTQYm1llGnGg2PENcjCh-M7HxGz9yCnshb5FoKJePGlDKZaKB_DXzSadXI_OWtW7d6MBuHTgztp-jqb4u-Eg32G-6jtCognz0mXkdC2jJ07pYFoL9V-CUzYibChYHbwF9xQgEoKBMO5RLVXpnul5eE8mHnOqjY13af8U6bNC7RYLuuYL5uj2wkY7guCKcHLKYNCvpYWTV_ezw-DqCEbR17fk8eqUHPByRaVh8mSUw0R7Jw